propose:
  description: >
    You're proposing the motion: {motion}.
    Come up with a clear argument in favor of the motion.
    Be very convincing.
  expected_output: >
    Your clear argument in favor of the motion, in a consice manner.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    You're in opposition to the motion: {motion}.
    Come up with a clear argument against the motion.
    Be very convincing.
  expected_output: >
    Your clear argument against the motion, in a consice manner.
  agent: debater
  output_file: output/oppose.md

decide:
  description:
    Review the arguments presented by the debaters and decide which side is more convincing.
  expected_output:
    Your decision which side is more convincing and why.
  agent: judge
  output_file: output/decide.md
